### ISSUE TITLE
Excluded Domains

### ISSUE THREAD

**Issue by boncuk10** [fyr77/dns-mobileconfig#22] opened 2023-05-07 13:43 UTC
Hi, how I can exclude domains in the profile creation? In nextdns i can do this:

![IMG_4883](https://user-images.githubusercontent.com/54523503/236681130-278ad719-eb3f-4520-a328-2ba205984492.jpeg)

**Comment by Gandulf78** [comment] 2023-05-08 06:51
Yes, it would be nice. 
The syntax is:

<dict>
					<key>Action</key>
					  <string>EvaluateConnection</string>
					<key>ActionParameters</key>
					<array>
						<dict>
							<key>DomainAction</key>
							<string>NeverConnect</string>
							<key>Domains</key>
							<array>
								<string>domaintoexclude.fr</string>
							</array>
						</dict>
					</array>
				</dict>

**Comment by fyr77** [comment] 2023-06-04 14:38
I am working on the implementation, but it will take a while longer because of university exams and deadlines. I will close this issue, since it is a duplicate of #14. Please watch that issue for progress.

**Closed by fyr77** 2023-06-04 14:38 UTC
Labels: duplicate
